version: '3.8'

services:
  
  zookeeper:
    image:
    ports:
    environment: 

  kafka:
    image:
    ports:
    environment: 
    depends_on: 

  redis:
    image: edis:6.0.6
    ports: 
      - "6379:6379"

  stedi:
    image: 
    ports: 
    environment: 
    depends_on: 
