version: '3.8'

services:
  
  zookeeper:
    image:
    ports:
    environment: 

  kafka:
    image:
    ports:
    environment: 
    depends_on: 

  redis:
    image: 
    ports: 

  stedi:
    image: scmurdock/stedi
    ports: 
    - "4567:4567"
    environment: 
      KAFKA_BROKER_ID: 
      KAFKA_ZOOKEEPER_CONNECT: 
      KAFKA_INTER_BROKER_LISTENER_NAME: 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 
    depends_on: 