version: '3.8'

services:
  
  zookeeper:
    image: confluentic/cp-zookeeper:5.5.1
    ports:
<<<<<<< HEAD
      -"2181:2181"
=======
      - "2181:2181"
>>>>>>> 272dd1e73ec2fc307f70f736bbd76c612d077092
    environment: 
      ZOOKEEPER_CLIENT_PORT: "2181"

  kafka:
    image: confluentinc/cp-kafka:5.2.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
      - "zookeeper" 

  redis:
    image: 
    ports: 

  stedi:
    image: scmurdock/stedi
    ports: 
    - "4567:4567"
    environment: 
      KAFKA_BROKER_ID: 
      KAFKA_ZOOKEEPER_CONNECT: 
      KAFKA_INTER_BROKER_LISTENER_NAME: 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 
    depends_on: 